import { ReactNode } from 'react'
import './globals.css'

import { Header } from '@/components/Header'
import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'

const notoSansJp = Noto_Sans_JP({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Book Commerce',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html lang="ja">
      <body className={notoSansJp.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
