import { ReactNode } from 'react'
import './globals.css'

import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import { NextAuthProvider } from './providers/NextAuthProvider'
import { ToasterProvider } from './providers/ToasterProvider'

const notoSansJp = Noto_Sans_JP({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Book Commerce',
  description: 'Generated by create next app',
}

const RootLayout = async ({
  children,
  header,
}: Readonly<Record<'children' | 'header', ReactNode>>) => {
  return (
    <html lang="ja">
      <body className={notoSansJp.className}>
        <ToasterProvider />
        {header}
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}

export default RootLayout
