import { ReactNode } from 'react'
import './globals.css'

import { Header } from '@/components/Header'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { Noto_Sans_JP } from 'next/font/google'
import { authOptions } from '../libs/authOptions'
import { NextAuthProvider } from './providers/NextAuthProvider'
import { ToasterProvider } from './providers/ToasterProvider'

const notoSansJp = Noto_Sans_JP({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Book Commerce',
  description: 'Generated by create next app',
}

const RootLayout = async ({ children }: Readonly<{ children: ReactNode }>) => {
  const session = await getServerSession(authOptions)

  return (
    <html lang="ja">
      <body className={notoSansJp.className}>
        <ToasterProvider />
        <Header session={session} />
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}

export default RootLayout
